# -*- coding: utf-8 -*-
"""adam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_HgxS5h7aapPioY4tnULbf0e3SiVhqd
"""

import matplotlib.pyplot as plt
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def binary_cross_entropy_loss(y_true, y_pred):
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return - (y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

def derivative_bce_loss(y_true, y_pred):
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    # The derivative dL/dy_pred for BCE
    return - (y_true / y_pred - (1 - y_true) / (1 - y_pred))

def gd_with_bce(w, b, learning_rate, x, y, max_iterations=1000, tolerance=0.0001):
    w_history = []
    b_history = []
    y_prd_history = []
    loss_history = [] # This will now store the actual BCE loss values

    for i in range(max_iterations):
        # Forward pass
        z = x * w + b
        y_prd = sigmoid(z)

        # Calculate actual BCE loss for monitoring
        current_bce_loss = binary_cross_entropy_loss(y, y_prd)
        loss_history.append(current_bce_loss)

        # Gradient of BCE loss with respect to y_prd
        dL_dy_prd = derivative_bce_loss(y, y_prd)

        # Store current values
        w_history.append(w)
        b_history.append(b)
        y_prd_history.append(y_prd)

        # Check for convergence based on a small change in weights or loss
        if np.abs(dL_dy_prd) * learning_rate < tolerance and i > 0:
            print(f"Converged (BCE) after {i+1} iterations.")
            break

        # Derivative of sigmoid with respect to z
        d_y_prd_d_z = y_prd * (1 - y_prd)

        # Apply chain rule to get gradients dL/dw and dL/db
        dL_dz = dL_dy_prd * d_y_prd_d_z
        d_w = dL_dz * x
        d_b = dL_dz * 1

        # Update weights and bias
        w = w - learning_rate * d_w
        b = b - learning_rate * d_b

    else:
        print(f"Did not converge within {max_iterations} iterations (BCE).")

    return w, b, w_history, b_history, y_prd_history, loss_history

def gd_with_adam_bce(w, b, learning_rate, x, y, beta1=0.9, beta2=0.999, epsilon=1e-8, max_iterations=1000, tolerance=0.0001):
    w_history = []
    b_history = []
    y_prd_history = []
    loss_history = []

    # Initialize Adam parameters
    m_dw, v_dw = 0, 0
    m_db, v_db = 0, 0

    for i in range(1, max_iterations + 1):
        # Forward pass
        z = x * w + b
        y_prd = sigmoid(z)

        # Calculate actual BCE loss for monitoring
        current_bce_loss = binary_cross_entropy_loss(y, y_prd)
        loss_history.append(current_bce_loss)

        # Gradient of BCE loss with respect to y_prd
        dL_dy_prd = derivative_bce_loss(y, y_prd)

        # Store current values
        w_history.append(w)
        b_history.append(b)
        y_prd_history.append(y_prd)

        # Check for convergence based on loss decreasing
        if current_bce_loss < tolerance and i > 1: # Added i > 1 to allow at least one update
            print(f"Converged (Adam) after {i} iterations.")
            break

        # Derivative of sigmoid with respect to z
        d_y_prd_d_z = y_prd * (1 - y_prd)

        # Apply chain rule to get gradients dL/dw and dL/db
        dL_dz = dL_dy_prd * d_y_prd_d_z
        d_w = dL_dz * x
        d_b = dL_dz * 1

        # Update biased first moment estimates
        m_dw = beta1 * m_dw + (1 - beta1) * d_w
        m_db = beta1 * m_db + (1 - beta1) * d_b

        # Update biased second raw moment estimates
        v_dw = beta2 * v_dw + (1 - beta2) * (d_w ** 2)
        v_db = beta2 * v_db + (1 - beta2) * (d_b ** 2)

        # Compute bias-corrected first moment estimates
        m_hat_dw = m_dw / (1 - beta1 ** i)
        m_hat_db = m_db / (1 - beta1 ** i)

        # Compute bias-corrected second raw moment estimates
        v_hat_dw = v_dw / (1 - beta2 ** i)
        v_hat_db = v_db / (1 - beta2 ** i)

        # Update weights and bias
        w = w - learning_rate * m_hat_dw / (np.sqrt(v_hat_dw) + epsilon)
        b = b - learning_rate * m_hat_db / (np.sqrt(v_hat_db) + epsilon)

    else:
        print(f"Did not converge within {max_iterations} iterations (Adam).")

    return w, b, w_history, b_history, y_prd_history, loss_history


# Run the gradient descent with BCE loss
initial_w_bce, initial_b_bce = 1, 2
learning_rate_bce = 0.01
x_val_bce, y_val_bce = 4, 1 # y_val for BCE should be 0 or 1

final_w_bce, final_b_bce, w_hist_bce, b_hist_bce, y_prd_hist_bce, loss_hist_bce = gd_with_bce(
    initial_w_bce, initial_b_bce, learning_rate_bce, x_val_bce, y_val_bce, max_iterations=1000, tolerance=0.0001
)

print(f'\nFinal w (with BCE): {final_w_bce:f}, Final b (with BCE): {final_b_bce:f}')
print(f'Final BCE Loss: {loss_hist_bce[-1]:f}')


# Run the gradient descent with Adam and BCE loss
initial_w_adam, initial_b_adam = 1, 2
learning_rate_adam = 0.01
x_val_adam, y_val_adam = 4, 1 # y_val for BCE should be 0 or 1

final_w_adam, final_b_adam, w_hist_adam, b_hist_adam, y_prd_hist_adam, loss_hist_adam = gd_with_adam_bce(
    initial_w_adam, initial_b_adam, learning_rate_adam, x_val_adam, y_val_adam, max_iterations=1000, tolerance=0.0001
)

print(f'\nFinal w (with Adam): {final_w_adam:f}, Final b (with Adam): {final_b_adam:f}')
print(f'Final BCE Loss (Adam): {loss_hist_adam[-1]:f}')