# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/SanthiniRa/342407c6045dcc60e4075d988da59d01/chatbot.ipynb

First step is add the openAI

common input and ouput
"""

user_input = input("How are you feeling today? ")
print("I understand. Tell me more about that.")

"""Load a Free AI Model"""

!pip install transformers torch accelerate

"""Load DialoGPT-medium from Hugging Face:"""

from transformers import pipeline

chatbot = pipeline("text-generation", model="microsoft/DialoGPT-medium")
#chatbot = pipeline("conversational", model="microsoft/DialoGPT-small")

Test generating responses:

def therapist_ai(user_input):
    prompt = f"Therapist: Respond empathetically.\nUser: {user_input}\nTherapist:"
    response = chatbot(prompt, max_length=150, do_sample=True, temperature=0.7)
    return response[0]['generated_text'].split("Therapist:")[-1]

print(therapist_ai("I feel stressed about work."))

prompt_test = f"Therapist: Respond empathetically.\nUser: {user_input}\nTherapist:"
response_test = chatbot(prompt_test, max_length=150, do_sample=True, temperature=0.7)
print(response_test)

while True:
    user = input("Hi. How are you feeling: ")
    if user.lower() == "quit":
        break
    print("Therapist:", therapist_ai(user))



system_prompt = """
You are a calm, empathetic therapist.
Listen carefully, validate feelings, and ask gentle reflective questions.
Do not give medical diagnosis.
"""
def therapist_ai(user_input):
    # Enhanced prompt to encourage more empathetic and detailed responses
    prompt = f"{system_prompt}\nUser: {user_input}\nTherapist: I hear you. It sounds like you're going through a lot. Can you tell me more about what's making you feel this way?"
    response = chatbot(prompt, max_new_tokens=100, do_sample=True, temperature=0.7)
    full_generated_text = response[0]['generated_text']

    # Extract only the part after the prompt (including the example response for better parsing)
    # The model might continue from the example, or start a new response
    expected_start_of_response = "Therapist: I hear you. It sounds like you're going through a lot. Can you tell me more about what's making you feel this way?"

    if full_generated_text.startswith(prompt):
        # If the model continues from the example, extract from there
        if full_generated_text.startswith(prompt + expected_start_of_response):
            print(full_generated_text)
            therapist_response = full_generated_text[len(prompt + expected_start_of_response):].strip()
        else:
            # If it rewrites the therapist part, find the last 'Therapist:'
            last_therapist_idx = full_generated_text.rfind("Therapist:")
            if last_therapist_idx != -1:
                therapist_response = full_generated_text[last_therapist_idx + len("Therapist:"):].strip()
            else:
                therapist_response = full_generated_text[len(prompt):].strip()
    else:
        # Fallback if model doesn't perfectly reproduce the prompt, find last 'Therapist:'
        last_therapist_idx = full_generated_text.rfind("Therapist:")
        if last_therapist_idx != -1:
            therapist_response = full_generated_text[last_therapist_idx + len("Therapist:"):].strip()
        else:
            therapist_response = full_generated_text.strip()

    return therapist_response if therapist_response else "I'm sorry, I couldn't generate a clear response. Can you tell me more?"

while True:
    user = input("How are You feeling: ")
    if user.lower() == "quit":
        break
    print("Therapist:", therapist_ai(user))