# -*- coding: utf-8 -*-
"""gdBinaryCrossEntropy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvHlkjMlXvWTig7mqbcjD7LJPlhVyXa9
"""

import matplotlib.pyplot as plt
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def binary_cross_entropy_loss(y_true, y_pred):
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return - (y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

def derivative_bce_loss(y_true, y_pred):
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    # The derivative dL/dy_pred for BCE
    return - (y_true / y_pred - (1 - y_true) / (1 - y_pred))

def gd_with_bce(w, b, learning_rate, x, y, max_iterations=1000, tolerance=0.001):
    w_history = []
    b_history = []
    y_prd_history = []
    loss_history = [] # This will now store the actual BCE loss values

    for i in range(max_iterations):
        # Forward pass
        z = x * w + b
        y_prd = sigmoid(z)

        # Calculate actual BCE loss for monitoring
        current_bce_loss = binary_cross_entropy_loss(y, y_prd)
        loss_history.append(current_bce_loss)

        # Gradient of BCE loss with respect to y_prd
        dL_dy_prd = derivative_bce_loss(y, y_prd)

        # Store current values
        w_history.append(w)
        b_history.append(b)
        y_prd_history.append(y_prd)

        # Check for convergence based on a small change in weights or loss
        # For simplicity, we can monitor the loss decreasing, or use a small step size
        # For this example, let's use the absolute value of dL_dy_prd for a quick convergence check
        if np.abs(dL_dy_prd) * learning_rate < tolerance:
            print(f"Converged after {i+1} iterations.")
            break

        # Derivative of sigmoid with respect to z
        d_y_prd_d_z = y_prd * (1 - y_prd)

        # Apply chain rule to get gradients dL/dw and dL/db
        # dL/dz = (dL/dy_prd) * (dy_prd/dz)
        dL_dz = dL_dy_prd * d_y_prd_d_z

        # dL/dw = (dL/dz) * (dz/dw) where dz/dw = x
        d_w = dL_dz * x
        # dL/db = (dL/dz) * (dz/db) where dz/db = 1
        d_b = dL_dz * 1

        # Update weights and bias
        w = w - learning_rate * d_w
        b = b - learning_rate * d_b

        # print(f'Iteration {i+1}: BCE Loss: {current_bce_loss:.4f}, y_prd: {y_prd:.4f}, w: {w:.4f}, b: {b:.4f}')

    else:
        print(f"Did not converge within {max_iterations} iterations.")

    return w, b, w_history, b_history, y_prd_history, loss_history

# Run the gradient descent with BCE loss
initial_w_bce, initial_b_bce = 1, 2
learning_rate_bce = 0.01
x_val_bce, y_val_bce = 4, 1 # y_val for BCE should be 0 or 1

final_w_bce, final_b_bce, w_hist_bce, b_hist_bce, y_prd_hist_bce, loss_hist_bce = gd_with_bce(
    initial_w_bce, initial_b_bce, learning_rate_bce, x_val_bce, y_val_bce, max_iterations=1000, tolerance=0.0001
)

print(f'\nFinal w (with BCE): {final_w_bce:f}, Final b (with BCE): {final_b_bce:f}')
print(f'Final BCE Loss: {loss_hist_bce[-1]:f}')

"""# Task
Summarize the optimization aspects of the given code, detailing the core Stochastic Gradient Descent mechanism, how `w` and `b` are updated based on the derivative of the implicit squared error loss function with respect to the sigmoid output, and identifying the absence of advanced optimization techniques such as mini-batching, adaptive learning rates (e.g., Adam, RMSprop), momentum, or regularization.

## Analyze Current Optimization

### Subtask:
Explain that the code uses a basic Gradient Descent algorithm to update `w` and `b` by iteratively minimizing a custom loss function. Detail how the derivative of the sigmoid function and the loss are used to calculate `d_w` and `d_b` for updates.

The `gd` function implements a basic Gradient Descent algorithm to optimize the parameters `w` (weight) and `b` (bias) for a single-variable logistic regression model. The optimization aims to minimize a custom loss function iteratively.

### Core Optimization Loop and Update Rules

Inside the `gd` function, the `for i in range(max_iterations):` loop represents the core of the iterative optimization process. In each iteration, `w` and `b` are updated using the following rules:

*   `w = w - learning_rate * d_w`
*   `b = b - learning_rate * d_b`

These are the standard update equations for Gradient Descent, where `learning_rate` controls the step size, and `d_w` and `d_b` are the gradients of the loss function with respect to `w` and `b`, respectively.

### Loss Function and Its Derivative

The code calculates `y_prd = sigmoid(z)`, where `z = x * w + b`. This `y_prd` is the model's prediction, transformed by the sigmoid activation function to a value between 0 and 1. The `loss` variable is then computed as:

*   `loss = 2 * (y_prd - y)`

While the comment states `loss=(y-y2)^2`, the implemented `loss` variable actually represents the **derivative of an implicit squared error loss function** `(y_prd - y)^2` with respect to `y_prd`. If the actual loss were `L = (y_prd - y)^2`, then its derivative with respect to `y_prd` would be `dL/d(y_prd) = 2 * (y_prd - y) * 1`, which precisely matches the `loss` calculation in the code.

### Gradient Calculation (`d_w` and `d_b`)

To update `w` and `b`, the gradients `d_w` and `d_b` are calculated using the chain rule, propagating the error backward through the sigmoid activation function:

1.  **Derivative of Sigmoid**: First, the derivative of the sigmoid activation function with respect to its input `z` is calculated:
    *   `d_y_prd_d_z = y_prd * (1 - y_prd)`
    This formula is a well-known property of the sigmoid function, where `y_prd` is `sigmoid(z)`.

2.  **Chain Rule Application**: With `dL/d(y_prd)` (represented by `loss`) and `d(y_prd)/dz` (represented by `d_y_prd_d_z`), we can apply the chain rule to find `dL/dz`. Then, using `z = x * w + b`, we find `dL/dw` and `dL/db`:
    *   `d_w = loss * d_y_prd_d_z * x`
        Here, `loss * d_y_prd_d_z` represents `dL/dz`. Since `dz/dw = x`, multiplying by `x` gives `dL/dw`.
    *   `d_b = loss * d_y_prd_d_z`
        Similarly, `loss * d_y_prd_d_z` is `dL/dz`. Since `dz/db = 1`, multiplying by `1` gives `dL/db`.

These calculated `d_w` and `d_b` values are then used in the Gradient Descent update rules to iteratively adjust `w` and `b` towards minimizing the loss.

## Identify Missing Advanced Optimizations

### Subtask:
Point out the absence of advanced optimization techniques such as mini-batch gradient descent, adaptive learning rate optimizers (e.g., Adam, RMSprop), momentum, or regularization (e.g., L1, L2). Also, note the use of a non-standard loss function for binary classification (Binary Cross-Entropy is typical with sigmoid output).

### Analysis of Advanced Optimizations and Loss Function

1.  **Batch Processing:** The `gd` function processes a single `x` and `y` value per update (`x_val`, `y_val` are single numbers passed to the function). This means it is effectively performing gradient descent on a single data point, not mini-batch or full batch gradient descent. In the context of a dataset, this would resemble a form of Stochastic Gradient Descent (SGD) if `x` and `y` were sampled, but as implemented, it's just updating based on one fixed example.

2.  **Adaptive Learning Rate Optimizers:** The `learning_rate` is a fixed hyperparameter (`learning_rate_val = 0.01`) that does not adapt during training. There are no mechanisms present for dynamically adjusting the learning rate based on past gradients, such as in Adam, RMSprop, or Adagrad.

3.  **Momentum:** The `gd` function does not incorporate momentum. The weight and bias updates (`w = w - learning_rate * d_w`, `b = b - learning_rate * d_b`) directly subtract the scaled gradient without considering the direction of previous updates.

4.  **Regularization (L1, L2):** There is no regularization applied. The loss function and gradient calculations do not include any terms (like L1 or L2 penalties) that would prevent overfitting by penalizing large weights.

5.  **Loss Function:** The loss function used is `loss = 2 * (y_prd - y)`. While the output `y_prd` is generated using a `sigmoid` activation function (which outputs probabilities between 0 and 1, typical for binary classification), this specific loss function is not the standard Binary Cross-Entropy (BCE) loss. BCE is given by `- (y * log(y_prd) + (1 - y) * log(1 - y_prd))`. The current loss function `2 * (y_prd - y)` is a simple linear difference multiplied by 2, which does not appropriately penalize errors in a probabilistic classification setting and can lead to issues during training, especially with probabilities close to 0 or 1. It also appears to be the derivative of a squared error `(y_prd - y)^2` with respect to `y_prd`, rather than a loss function itself.

## Suggest Improvements (Optional)

### Subtask:
Briefly suggest potential improvements to the optimization aspect of the code, such as using a standard binary cross-entropy loss, implementing mini-batching, or integrating an adaptive optimizer.

### Potential Improvements to the Optimization Aspect

1.  **Standardize Loss Function:** The current `loss = 2 * (y_prd - y)` is a custom loss function. For probabilistic outputs from a sigmoid activation, a standard **Binary Cross-Entropy (BCE) loss** is more appropriate and generally leads to better performance and convergence. BCE loss properly penalizes the model based on the probability output and the true label.

2.  **Implement Mini-Batch Gradient Descent:** For larger datasets, implementing **mini-batch gradient descent** would significantly speed up training and provide a more stable gradient estimate compared to full batch gradient descent or stochastic gradient descent (if `x` and `y` were single samples). This involves processing data in small batches rather than one sample at a time or all samples at once.

3.  **Integrate Adaptive Optimizers:** Instead of a fixed `learning_rate`, incorporating **adaptive optimization algorithms** like Adam, RMSprop, or Adagrad would be beneficial. These optimizers automatically adjust the learning rate for each parameter, often leading to faster convergence and more stable training, especially in complex models or when tuning the learning rate manually is challenging.

4.  **Add Regularization Techniques:** To prevent overfitting, especially when dealing with more complex models or limited data, **regularization techniques** such as L1 (Lasso) or L2 (Ridge) could be added to the loss function. This helps to constrain the weights and reduce model complexity, improving generalization to unseen data.

## Final Task

### Subtask:
Summarize the optimization aspects of the given code, distinguishing between the core Gradient Descent mechanism present and the more advanced techniques that are absent.

## Summary:

### Data Analysis Key Findings
*   The `gd` function implements a basic Gradient Descent algorithm, updating weights `w` and bias `b` iteratively using the rules `w = w - learning_rate * d_w` and `b = b - learning_rate * d_b`.
*   The variable `loss = 2 * (y_prd - y)` in the code represents the derivative of an implicit squared error loss function `(y_prd - y)^2` with respect to the sigmoid output `y_prd`, rather than a standalone loss function.
*   Gradients `d_w` and `d_b` are calculated using the chain rule, incorporating the sigmoid derivative `d_y_prd_d_z = y_prd * (1 - y_prd)`, resulting in `d_w = loss * d_y_prd_d_z * x` and `d_b = loss * d_y_prd_d_z`.
*   The current optimization method processes a single data point per update, resembling Stochastic Gradient Descent if sampled, but lacks full mini-batch or full batch processing.
*   No advanced optimization techniques are present: the `learning_rate` is fixed at `0.01` without adaptive adjustment (e.g., Adam, RMSprop), momentum is not incorporated, and regularization (L1, L2) is absent.
*   The utilized loss function `loss = 2 * (y_prd - y)` is non-standard for binary classification with a sigmoid output; the typical and more appropriate loss function is Binary Cross-Entropy (BCE).

### Insights or Next Steps
*   **Standardize Loss Function:** Replace the custom loss with a standard Binary Cross-Entropy (BCE) loss, which is more suitable for probabilistic outputs from a sigmoid activation in binary classification.
*   **Implement Advanced Optimizers:** Introduce mini-batch gradient descent for more efficient training on larger datasets, and integrate adaptive optimization algorithms such as Adam, RMSprop, or Adagrad to improve convergence speed and stability.
*   **Add Regularization:** Apply regularization techniques like L1 or L2 penalties to the loss function to mitigate overfitting, especially for more complex models or limited data.

### Binary Cross-Entropy (BCE) Loss

For binary classification problems where the output `y_prd` is a probability (between 0 and 1) representing the likelihood of the positive class, Binary Cross-Entropy (BCE) is the standard and most appropriate loss function. It is defined as:

$L = - (y \cdot \log(y_{prd}) + (1 - y) \cdot \log(1 - y_{prd}))$

Where:
*   `y` is the true label (0 or 1)
*   `y_prd` is the predicted probability of the positive class
*   $\log$ is the natural logarithm

The goal of the optimization is to minimize this loss function. When `y` is 1, the loss term becomes $- \log(y_{prd})$, which approaches 0 as $y_{prd}$ approaches 1. When `y` is 0, the loss term becomes $- \log(1 - y_{prd})$, which approaches 0 as $y_{prd}$ approaches 0. This function heavily penalizes confident wrong predictions.

### Derivative of BCE Loss

To use BCE in gradient descent, we also need its derivative with respect to `y_prd`:

$\frac{dL}{dy_{prd}} = - \left( \frac{y}{y_{prd}} - \frac{1 - y}{1 - y_{prd}} \right)$
"""

import numpy as np

def binary_cross_entropy_loss(y_true, y_pred):
    # Clip y_pred to avoid log(0) which results in NaN or infinite loss
    epsilon = 1e-10 # A very small number to prevent log(0)
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return - (y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

def derivative_bce_loss(y_true, y_pred):
    # Derivative of BCE loss with respect to y_pred
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return - (y_true / y_pred - (1 - y_true) / (1 - y_pred))

# Example usage:
y_true = 1
y_pred = 0.9
print(f"BCE Loss (y_true={y_true}, y_pred={y_pred}): {binary_cross_entropy_loss(y_true, y_pred)}")
print(f"Derivative of BCE Loss (y_true={y_true}, y_pred={y_pred}): {derivative_bce_loss(y_true, y_pred)}")

y_true = 0
y_pred = 0.1
print(f"BCE Loss (y_true={y_true}, y_pred={y_pred}): {binary_cross_entropy_entropy_loss(y_true, y_pred)}")
print(f"Derivative of BCE Loss (y_true={y_true}, y_pred={y_pred}): {derivative_bce_loss(y_true, y_pred)}")

"""### Integrating BCE into the `gd` function

Now, let's modify the `gd` function to use the Binary Cross-Entropy loss. This involves replacing the `loss` calculation and adjusting the `d_w` and `d_b` calculations accordingly. Specifically, the `loss` variable in the original code actually represented `dL/d(y_prd)`. We will replace that with the `derivative_bce_loss` calculation.
"""

import matplotlib.pyplot as plt
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def binary_cross_entropy_loss(y_true, y_pred):
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return - (y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

def derivative_bce_loss(y_true, y_pred):
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    # The derivative dL/dy_pred for BCE
    return - (y_true / y_pred - (1 - y_true) / (1 - y_pred))

def gd_with_bce(w, b, learning_rate, x, y, max_iterations=1000, tolerance=0.001):
    w_history = []
    b_history = []
    y_prd_history = []
    loss_history = [] # This will now store the actual BCE loss values

    for i in range(max_iterations):
        # Forward pass
        z = x * w + b
        y_prd = sigmoid(z)

        # Calculate actual BCE loss for monitoring
        current_bce_loss = binary_cross_entropy_loss(y, y_prd)
        loss_history.append(current_bce_loss)

        # Gradient of BCE loss with respect to y_prd
        dL_dy_prd = derivative_bce_loss(y, y_prd)

        # Store current values
        w_history.append(w)
        b_history.append(b)
        y_prd_history.append(y_prd)

        # Check for convergence based on a small change in weights or loss
        # For simplicity, we can monitor the loss decreasing, or use a small step size
        # For this example, let's use the absolute value of dL_dy_prd for a quick convergence check
        if np.abs(dL_dy_prd) * learning_rate < tolerance:
            print(f"Converged after {i+1} iterations.")
            break

        # Derivative of sigmoid with respect to z
        d_y_prd_d_z = y_prd * (1 - y_prd)

        # Apply chain rule to get gradients dL/dw and dL/db
        # dL/dz = (dL/dy_prd) * (dy_prd/dz)
        dL_dz = dL_dy_prd * d_y_prd_d_z

        # dL/dw = (dL/dz) * (dz/dw) where dz/dw = x
        d_w = dL_dz * x
        # dL/db = (dL/dz) * (dz/db) where dz/db = 1
        d_b = dL_dz * 1

        # Update weights and bias
        w = w - learning_rate * d_w
        b = b - learning_rate * d_b

        # print(f'Iteration {i+1}: BCE Loss: {current_bce_loss:.4f}, y_prd: {y_prd:.4f}, w: {w:.4f}, b: {b:.4f}')

    else:
        print(f"Did not converge within {max_iterations} iterations.")

    return w, b, w_history, b_history, y_prd_history, loss_history

# Run the gradient descent with BCE loss
initial_w_bce, initial_b_bce = 1, 2
learning_rate_bce = 0.01
x_val_bce, y_val_bce = 4, 1 # y_val for BCE should be 0 or 1

final_w_bce, final_b_bce, w_hist_bce, b_hist_bce, y_prd_hist_bce, loss_hist_bce = gd_with_bce(
    initial_w_bce, initial_b_bce, learning_rate_bce, x_val_bce, y_val_bce, max_iterations=1000, tolerance=0.0001
)

print(f'\nFinal w (with BCE): {final_w_bce:f}, Final b (with BCE): {final_b_bce:f}')
print(f'Final BCE Loss: {loss_hist_bce[-1]:f}')