# -*- coding: utf-8 -*-
"""gdPynumSigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mkNUkyB_Oq3gE4QVYAnTDh4OxEx_vNy2
"""

import numpy as np
import matplotlib.pyplot as plt

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def binary_cross_entropy(y_true, y_pred, epsilon=1e-10):
    # Clip y_pred to avoid log(0) errors
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

def gd(w, b, learning_rate, x, y, max_iterations=1000, tolerance=0.01):
    # Ensure x and y are numpy arrays
    x = np.array(x)
    y = np.array(y)

    loss_history = [] # Store loss at each iteration

    for i in range(max_iterations):
        z = x * w + b
        y_prd = sigmoid(z)

        # a. Replace MSE loss with Binary Cross-Entropy
        loss = binary_cross_entropy(y, y_prd)
        loss_history.append(loss) # Append current loss to history

        if loss < tolerance:
            print(f"Converged after {i+1} iterations.")
            break

        # b. Update derivatives for BCE loss with sigmoid activation
        # d(Loss)/d(z) = y_prd - y_true for BCE with sigmoid
        #d_loss_d_z = y_prd - y
        d_loss_d_z = y_prd * (1 - y_prd)

        # c. Compute d_w and d_b as the mean over all samples
        d_w = np.mean(d_loss_d_z * x)
        d_b = np.mean(d_loss_d_z)

        w = w - learning_rate * d_w
        b = b - learning_rate * d_b

        if (i + 1) % 100 == 0 or i == 0: # Print less frequently for clarity with arrays
            print(f'Iteration {i+1}:')
            print(f'  Loss: {loss:f}') # d. Update print statement for Loss
            print(f'  Predicted (first 5): {y_prd[:5]}...') # d. Update print statement for y_prd
            #print(f'  w: {w:f}, b: {b:f}')
            #print(f'  d_w: {d_w:f}, d_b: {d_b:f}') # This line was commented out in original, keeping it commented
    else:
        print(f"Did not converge within {max_iterations} iterations.")

    return w, b, loss_history # Return loss_history as well

# Example usage with NumPy arrays
x_data = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
y_data = np.array([0, 0, 0, 1, 1]) # Updated y_data to be binary for BCE

initial_w = 0.5
initial_b = 0.5
learning_rate = 0.01

print(f"\nStarting Gradient Descent with NumPy...")
final_w, final_b, loss_hist = gd(initial_w, initial_b, learning_rate, x_data, y_data, max_iterations=10000, tolerance=0.001)
print(f'\nFinal w: {final_w:f}, Final b: {final_b:f}')

# Plot the loss history
plt.figure(figsize=(10, 6))
plt.plot(loss_hist, label='Binary Cross-Entropy Loss')
plt.title('Loss over Iterations')
plt.xlabel('Iteration')
plt.ylabel('Loss')
plt.grid(True)
plt.legend()
plt.show()