# -*- coding: utf-8 -*-
"""gdWithGraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONQshEb2cCoWt0qbtux7a2x_sBm91Lqy
"""

import matplotlib.pyplot as plt

def gd(w, b, learning_rate, x, y, max_iterations=1000, tolerance=0.01):
    w_history = []
    b_history = []
    y_prd_history = []
    loss_history = []

    for i in range(max_iterations):
        y_prd = x * w + b # y=mx+c
        loss = (y - y_prd) ** 2 # loss=(y-y2)^2

        w_history.append(w)
        b_history.append(b)
        y_prd_history.append(y_prd)
        loss_history.append(loss)

        if loss < tolerance:
            print(f"Converged after {i+1} iterations.")
            break

        d_w = 2 * (y_prd - y) * x # math calculation of diff of weight by loss
        d_b = 2 * (y_prd - y) # math calculation of diff of bias by loss

        w = w - learning_rate * d_w
        b = b - learning_rate * d_b

        # print(f'Iteration {i+1}:')
        # print(f'  x: {x:f}, y: {y:f}')
        # print(f'  loss: {loss:f}')
        # print(f'  y_prd: {y_prd:f}')
        # print(f'  w: {w:f}, b: {b:f}')
        # print(f'  d_w: {d_w:f}, d_b: {d_b:f}')
    else:
        print(f"Did not converge within {max_iterations} iterations.")

    return w, b, w_history, b_history, y_prd_history, loss_history

# Run the gradient descent and capture the history
initial_w, initial_b = 1, 2
learning_rate_val = 0.01 # Adjusted learning rate for better visualization if needed
x_val, y_val = 4, 5

final_w, final_b, w_hist, b_hist, y_prd_hist, loss_hist = gd(
    initial_w, initial_b, learning_rate_val, x_val, y_val, max_iterations=1000, tolerance=0.001
)

print(f'\nFinal w: {final_w:f}, Final b: {final_b:f}')

import matplotlib.pyplot as plt

# Plotting w_history
plt.figure(figsize=(10, 5))
plt.plot(w_hist, marker='o', linestyle='-', color='blue')
plt.title('Weight (w) over Iterations')
plt.xlabel('Iteration')
plt.ylabel('Weight (w)')
plt.grid(True)
plt.show()

# Plotting b_history
plt.figure(figsize=(10, 5))
plt.plot(b_hist, marker='o', linestyle='-', color='red')
plt.title('Bias (b) over Iterations')
plt.xlabel('Iteration')
plt.ylabel('Bias (b)')
plt.grid(True)
plt.show()



